set_location_assignment PIN_R8  -to clk_i
set_location_assignment PIN_E1  -to rst_n_i
set_location_assignment PIN_L3  -to leds_o[7]
set_location_assignment PIN_B1  -to leds_o[6]
set_location_assignment PIN_F3  -to leds_o[5]
set_location_assignment PIN_D1  -to leds_o[4]
set_location_assignment PIN_A11 -to leds_o[3]
set_location_assignment PIN_B13 -to leds_o[2]
set_location_assignment PIN_A13 -to leds_o[1]
set_location_assignment PIN_A15 -to leds_o[0]
